version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8876:80
    container_name: project_nginx
    depends_on:
      - app

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: project_app
    depends_on:
        - db

  db:
    image: mysql:8.0.32
    volumes:
       - ./tmp/db2:/var/lib/mysql
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: root
    ports:
        - 8101:3306
    command: --lower_case_table_names=1
    container_name: project_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - 8080:80
    environment:
        - PMA_ARBITRARY=1
    depends_on:
        - db
